component_depth: 1
languages:
- java

exclude:
- /android/assets/.*
- /android/build/.*
- /android/libs/.*
- /android/res/.*
- /BaseGameUtils/.*
- /build/*
- /desktop/build/.*
- /gradle/*
- /html/*
- /ios/*
- /core/build/*
